# Collaboration and Competition

---

In this notebook, you will learn how to use the Unity ML-Agents environment for the third project of the [Deep Reinforcement Learning Nanodegree](https://www.udacity.com/course/deep-reinforcement-learning-nanodegree--nd893) program.

### 1. Start the Environment

We begin by importing the necessary packages.  If the code cell below returns an error, please revisit the project instructions to double-check that you have installed [Unity ML-Agents](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md) and [NumPy](http://www.numpy.org/).

Next, we will start the environment!  **_Before running the code cell below_**, change the `file_name` parameter to match the location of the Unity environment that you downloaded.

- **Mac**: `"path/to/Tennis.app"`
- **Windows** (x86): `"path/to/Tennis_Windows_x86/Tennis.exe"`
- **Windows** (x86_64): `"path/to/Tennis_Windows_x86_64/Tennis.exe"`
- **Linux** (x86): `"path/to/Tennis_Linux/Tennis.x86"`
- **Linux** (x86_64): `"path/to/Tennis_Linux/Tennis.x86_64"`
- **Linux** (x86, headless): `"path/to/Tennis_Linux_NoVis/Tennis.x86"`
- **Linux** (x86_64, headless): `"path/to/Tennis_Linux_NoVis/Tennis.x86_64"`

For instance, if you are using a Mac, then you downloaded `Tennis.app`.  If this file is in the same folder as the notebook, then the line below should appear as follows:
```
env = UnityEnvironment(file_name="Tennis.app")
```

Environments contain **_brains_** which are responsible for deciding the actions of their associated agents. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.

### 2. Examine the State and Action Spaces

In this environment, two agents control rackets to bounce a ball over a net. If an agent hits the ball over the net, it receives a reward of +0.1.  If an agent lets a ball hit the ground or hits the ball out of bounds, it receives a reward of -0.01.  Thus, the goal of each agent is to keep the ball in play.

The observation space consists of 8 variables corresponding to the position and velocity of the ball and racket. Two continuous actions are available, corresponding to movement toward (or away from) the net, and jumping. 

Run the code cell below to print some information about the environment.

In [1]:
from unityagents import UnityEnvironment
import numpy as np

env = UnityEnvironment(file_name="Tennis_Linux/Tennis.x86_64")#, no_graphics = True)
# get the default brain
brain_name = env.brain_names[0]
brain = env.brains[brain_name]

# reset the environment
env_info = env.reset(train_mode=True)[brain_name]

# number of agents 
num_agents = len(env_info.agents)
print('Number of agents:', num_agents)

# size of each action
action_size = brain.vector_action_space_size
print('Size of each action:', action_size)

# examine the state space 
states = env_info.vector_observations
state_size = states.shape[1]
print('There are {} agents. Each observes a state with length: {}'.format(states.shape[0], state_size))
print('The state for the first agent looks like:', states[0])

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		
Unity brain name: TennisBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 3
        Vector Action space type: continuous
        Vector Action space size (per agent): 2
        Vector Action descriptions: , 


Number of agents: 2
Size of each action: 2
There are 2 agents. Each observes a state with length: 24
The state for the first agent looks like: [ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.         -6.65278625 -1.5
 -0.          0.          6.83172083  6.         -0.          0.        ]


### 3. Take Random Actions in the Environment

In the next code cell, you will learn how to use the Python API to control the agents and receive feedback from the environment.

Once this cell is executed, you will watch the agents' performance, if they select actions at random with each time step.  A window should pop up that allows you to observe the agents.

Of course, as part of the project, you'll have to change the code so that the agents are able to use their experiences to gradually choose better actions when interacting with the environment!

When finished, you can close the environment.

### 4. It's Your Turn!

Now it's your turn to train your own agent to solve the environment!  When training the environment, set `train_mode=True`, so that the line for resetting the environment looks like the following:
```python
env_info = env.reset(train_mode=True)[brain_name]
```

In [ ]:
from unityagents import UnityEnvironment
import numpy as np

env = UnityEnvironment(file_name="Tennis_Linux/Tennis.x86_64")#, no_graphics = True)
# get the default brain
brain_name = env.brain_names[0]
brain = env.brains[brain_name]

# reset the environment
env_info = env.reset(train_mode=True)[brain_name]

# number of agents 
num_agents = len(env_info.agents)
print('Number of agents:', num_agents)

# size of each action
action_size = brain.vector_action_space_size
print('Size of each action:', action_size)

# examine the state space 
states = env_info.vector_observations
state_size = states.shape[1]
print('There are {} agents. Each observes a state with length: {}'.format(states.shape[0], state_size))
print('The state for the first agent looks like:', states[0])




%load_ext autoreload
%autoreload 2

import torch
from matplotlib import pyplot as plt
from ddpg_agent import Agent
from collections import deque

env_info = env.reset(train_mode=True)[brain_name]
states = env_info.vector_observations
action_size = brain.vector_action_space_size
state_size = states.shape[1]



print_every = 30
n_episodes= 4000 # 2000
max_t=1000
Batch_size = 64# 512
N_Bootstrap = 8  ## New
Learning_Rate = 10
seed = 8



def ddpg(env,agent, print_every, n_episodes, max_t, Batch_size, N_Bootstrap, seed):
    scores_deque = deque(maxlen=print_every)
    for i_episode in range(0, n_episodes+1):
        env_info = env.reset(train_mode=True)[brain_name]
        agent.reset()
        states = env_info.vector_observations
        score = np.asarray([0.,0.])
        reduction =((n_episodes-i_episode+0.0)/(n_episodes+0.0))**15
        for t in range(max_t):
            action0 = agent.act(np.asarray([states[0]]),reduction) #states[0]
            action1 = agent.act(np.asarray([states[1]]),reduction) #states[0]
            env_info = env.step([action0,action1])[brain_name]           # send all actions to tne environment
            next_states = env_info.vector_observations         # get next state (for each agent)
            rewards = env_info.rewards                         # get reward (for each agent)
            dones = env_info.local_done                        # see if episode finished
            score += np.asarray(env_info.rewards)
            agent.step(states[0], action0[0], rewards[0], next_states[0], dones[0])
            agent.step(states[1], action1[0], rewards[1], next_states[1], dones[1])
            states = next_states
            if dones[0]:
                break
        scores_deque.append(score)
        if i_episode % print_every == 0:
            print('\rEpisode {}\tAverage Score: {:.4f}'.format(i_episode, np.mean(scores_deque)))
            #print (reduction)
            #print (states[0])
            #print (action0)
            #print (states[1])
            #print (action1)           
            torch.save(agent.actor_local.state_dict(), 'checkpoint_actor_.pth')
            torch.save(agent.critic_local.state_dict(), 'checkpoint_critic_.pth')
    return scores_deque

agent = Agent(state_size, action_size, seed, Batch_size, Learning_Rate, N_Bootstrap)
scores = ddpg(env,agent, print_every, n_episodes, max_t, Batch_size, N_Bootstrap, seed)
torch.save(agent.actor_local.state_dict(), 'checkpoint_actor_'+str(seed)+".pth")
torch.save(agent.critic_local.state_dict(), 'checkpoint_critic_'+str(seed)+".pth")

In [3]:
a = np.vstack([e.reward for e in agent.memory.memory if e is not None])
b = agent.memory.prios

In [4]:
len(a[a>0])
np.where(a>0)

(array([  292,   708,  1079,  7079,  7823,  8145,  8252,  9071, 10163,
        10304, 10556, 10646, 11246, 11342, 11603, 11752, 12126, 12433,
        13093, 13387, 14312, 14459, 14918]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0]))

In [5]:
agent = Agent(state_size, action_size, seed, Batch_size, Learning_Rate, N_Bootstrap)
agent.reset()
next_state= torch.FloatTensor([next_states[1]])
state = torch.FloatTensor([states[1]])
action0 = agent.act(np.asarray([states[1]]),1)[0]
action = torch.FloatTensor([action0])

print (agent.critic_target(state, action))
print (agent.critic_local(state, action))

NameError: name 'next_states' is not defined

In [4]:
print (np.mean(np.asarray(b)[[np.where(a>0)][0][0]]))
print (np.mean(np.asarray(b)[[np.where(a<0)][0][0]]))
print (np.mean(np.asarray(b)[[np.where(a==0)][0][0]]))

0.049400998604439555
0.005968637593173023
0.002796234717440362


In [7]:
####### Random #####

states_ = []
rewards_= []
for i in range(1, 20):                                      # play game for 5 episodes
    env_info = env.reset(train_mode=False)[brain_name]     # reset the environment    
    states = env_info.vector_observations                  # get the current state (for each agent)
    scores = np.zeros(num_agents)                          # initialize the score (for each agent)
    while True:
        actions = np.random.randn(num_agents, action_size) # select an action (for each agent)
        actions = np.clip(actions, -1, 1)                  # all actions between -1 and 1
        env_info = env.step(actions)[brain_name]           # send all actions to tne environment
        next_states = env_info.vector_observations         # get next state (for each agent)
        rewards = env_info.rewards                         # get reward (for each agent)
        rewards_.append(rewards)
        dones = env_info.local_done                        # see if episode finished
        scores += env_info.rewards                         # update the score (for each agent)
        states = next_states                               # roll over states to next time step
        states_.append(states)
        if np.any(dones):                                  # exit loop if episode finished
            break
    print('Score (max over agents) from episode {}: {}'.format(i, np.max(scores)))

Score (max over agents) from episode 1: 0.0
Score (max over agents) from episode 2: 0.10000000149011612


KeyboardInterrupt: 

In [10]:
states

array([[ -7.0517621 ,  -1.5       ,  -0.        ,   0.        ,
          6.14030886,   5.98822832,  -0.        ,   0.        ,
         -6.37289381,  -1.55886006,   6.78869152,  -0.98100001,
          6.14030886,   5.89012814,   6.78869152,  -0.98100001,
         -9.14631271,  -1.71581995, -27.73419189,  -1.96200001,
          6.14030886,   5.69392824, -27.73419189,  -1.96200001],
       [ -7.05968189,  -1.5       ,   0.        ,   0.        ,
         -6.14030886,   5.98822832,   0.        ,   0.        ,
         -5.23611116,  -1.55886006,  18.23569679,  -0.98100001,
         -6.14030886,   5.89012814,  18.23569679,  -0.98100001,
         -4.0152173 ,  -1.71581995,  12.20893383,  -1.96200001,
         -6.14030886,   5.69392824,  12.20893383,  -1.96200001]])

In [11]:
actions

array([[-0.05480195,  0.95768507],
       [-0.59935207, -0.38196059]])